[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
pidfile=/var/run/supervisord.pid
user=root

[program:php-fpm]
command=php-fpm --nodaemonize
autostart=true
autorestart=true
priority=10
startretries=3
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm-err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
