services:
  # Nginx Web Server (Tribe)
  nginx_tribe:
    image: nginx:alpine
    container_name: nginx_tribe
    restart: unless-stopped
    ports:
      - "${TRIBE_PORT:-1212}:80"
    volumes:
      - ./applications/tribe:/var/www/html
      - ./applications/phpmyadmin:/var/www/html/phpmyadmin
      - ./uploads:/var/www/html/uploads
      - ./config/tribe/config.php:/var/www/html/config/config.php
      - ./config/tribe/phpmyadmin.config.inc.php:/var/www/html/phpmyadmin/config.inc.php
      - ./.env:/var/www/html/.env
      - ./logs:/var/log/nginx
      - ./config/tribe/conf.d/tribe.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_tribe
    networks:
      - lemp_network

  # PHP 8 with FPM for Tribe
  php_tribe:
    build:
      context: ./config/tribe
      dockerfile: Dockerfile
    container_name: php_tribe
    restart: unless-stopped
    volumes:
      - ./applications/tribe:/var/www/html
      - ./applications/phpmyadmin:/var/www/html/phpmyadmin
      - ./uploads:/var/www/html/uploads
      - ./config/tribe/phpmyadmin.config.inc.php:/var/www/html/phpmyadmin/config.inc.php
      - ./.env:/var/www/html/.env
      - ./logs:/var/log
      - ./config/tribe/php.ini:/usr/local/etc/php/php.ini
      - ./config/tribe/config.php:/var/www/html/config/config.php
    command: >
      sh -c "composer install --no-interaction --optimize-autoloader &&
           php-fpm"
    depends_on:
      - mysql
    networks:
      - lemp_network

  # Nginx Web Server (Junction)
  nginx_junction:
    image: nginx:alpine
    container_name: nginx_junction
    restart: unless-stopped
    ports:
      - "${JUNCTION_PORT:-4488}:80"
    volumes:
      - ./applications/junction/dist:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./.env:/var/www/html/.env
      - ./config/junction/config.php:/var/www/html/config/config.php
      - ./logs:/var/log/nginx
      - ./config/junction/conf.d/junction.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_junction
    networks:
      - lemp_network

  # PHP 8 with FPM for Junction
  php_junction:
    build:
      context: ./config/junction
      dockerfile: Dockerfile
    container_name: php_junction
    restart: unless-stopped
    volumes:
      - ./applications/junction/dist:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./.env:/var/www/html/.env
      - ./logs:/var/log
      - ./config/junction/php.ini:/usr/local/etc/php/php.ini
      - ./config/junction/config.php:/var/www/html/config/config.php
    command: >
      sh -c "composer install --no-interaction --optimize-autoloader &&
           php-fpm"
    depends_on:
      - mysql
    networks:
      - lemp_network

  # MySQL 9 Database
  mysql:
    image: mysql:9
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tribe_db
      MYSQL_USER: tribe_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./uploads/mysql:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - lemp_network

# Networks
networks:
  lemp_network:
    driver: bridge
