apiVersion: v1
kind: Service
metadata:
  name: php-tribe
  namespace: tribe-junction
  labels:
    app: php-tribe
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: php-fpm
  selector:
    app: php-tribe

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-tribe
  namespace: tribe-junction
  labels:
    app: php-tribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-tribe
  template:
    metadata:
      labels:
        app: php-tribe
    spec:
      initContainers:
      - name: setup
        image: yourusername/tribe-junction-setup:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        command: ["/setup.sh"]
      containers:
      - name: php-tribe
        image: yourusername/tribe-junction-php-tribe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        # Database connection
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS
        # App configuration
        - name: SSL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SSL
        - name: DISPLAY_ERRORS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DISPLAY_ERRORS
        - name: ALLOW_API_FULL_ACCESS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ALLOW_API_FULL_ACCESS
        - name: DEFAULT_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEFAULT_TIMEZONE
        # URLs will be set via service discovery
        - name: TRIBE_BARE_URL
          value: "localhost:1212"
        - name: TRIBE_URL
          value: "http://localhost:1212"
        - name: TRIBE_PORT
          value: "1212"
        volumeMounts:
        - name: tribe-code
          mountPath: /var/www/html
        - name: shared-data
          mountPath: /var/www/html/phpmyadmin
          subPath: applications/phpmyadmin
        - name: uploads
          mountPath: /var/www/html/uploads
        - name: logs
          mountPath: /var/log
        workingDir: /var/www/html
        command: ["sh", "-c"]
        args: 
        - |
          composer install --no-interaction --optimize-autoloader
          php-fpm
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tribe-code
        hostPath:
          path: ./applications/tribe  # This will need to be absolute path
          type: Directory
      - name: shared-data
        emptyDir: {}
      - name: uploads
        hostPath:
          path: ./uploads
          type: DirectoryOrCreate
      - name: logs
        hostPath:
          path: ./logs
          type: DirectoryOrCreate